// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/forecasts/{latitude}/{longitude}": {
            "get": {
                "description": "Get Forecast By Coordinates",
                "produces": [
                    "application/json"
                ],
                "summary": "Returns the forecasted weather by latitude and longitude coordinates",
                "operationId": "get-forecast-by-coordinates",
                "parameters": [
                    {
                        "type": "number",
                        "format": "float",
                        "description": "The latitude of the desired location  (e.g. 39.7456)",
                        "name": "latitude",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "format": "flaot",
                        "description": "The longitude of the desired location  (e.g. -97.0892)",
                        "name": "longitude",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Forecast"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.Characterization": {
            "type": "string",
            "enum": [
                "hot",
                "cold",
                "moderate",
                "unknown "
            ],
            "x-enum-varnames": [
                "Hot",
                "Cold",
                "Moderate",
                "Unknown"
            ]
        },
        "models.Forecast": {
            "type": "object",
            "properties": {
                "forecast_daily": {
                    "type": "string"
                },
                "temperature": {
                    "type": "integer"
                },
                "temperature_characterization": {
                    "$ref": "#/definitions/models.Characterization"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Weather API",
	Description:      "This is an HTTP server that serves the forecasted weather",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
